services:
  postgres:
    container_name: psql_container_books_project
    image: postgres
    environment:
      POSTGRES_USER: realcj
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres_books_project:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - book-project-network
    restart: unless-stopped


  mail-dev:
    container_name: maildev_books_project
    image: maildev/maildev
    ports:
      - "1080:1080"  # HTTP Web UI
      - "1025:1025"  # SMTP Server

#  project-api:
#    container_name: project_api_books_project
#    image: chamikajay/spring-book-api
#    ports:
#      - "8080:8080"
#    networks:
#      - book-project-network
#    depends_on:
#      - postgres
#      - mail-dev
#    volumes:
#      - api-storage:/app/storage
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/books-network
#



networks:
  book-project-network:
    driver: bridge

volumes:
  postgres_books_project:
  api-storage:
    driver: local